languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Ryan P. Meyer"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["posts"]
  description = "Something my own."

[params.author]
  name = "Ryan P. Meyer"
  # image = "img/author.jpg"
  headline = "Mistakes Included, No Extra Charge"
  # bio = "A technology enthusiast"
  links = [
    { email = "mailto:hello@ryanpmeyer.eu" },
    { linkedin = "https://linkedin.com/in/ryanpmeyer" },
    { bluesky = "https://bsky.app/profile/ryanpmeyer.eu"},
    { github = "https://github.com/codeonrye" },
  ]
